version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    environment:
      CIRCLE_ARTIFACTS: /tmp/circle-artifacts
    steps:
      - add_ssh_keys
      - checkout
      - run: sudo apt-get install -y libsndfile1 libsndfile1-dev
      - run: npm install
      - run: npm test
      - run: sudo npm link
      - run: mkdir -p $CIRCLE_ARTIFACTS
      - run: bms-renderer fixtures/cut.bms $CIRCLE_ARTIFACTS/cut.wav
      - run: bms-renderer --full fixtures/cut.bms $CIRCLE_ARTIFACTS/cut.wav
      - run: ./mkdist
      - store_artifacts:
          path: /tmp/circle-artifacts
          destination: artifacts
