version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.9.1
    environment:
      CIRCLE_ARTIFACTS: /tmp/circle-artifacts
    steps:
      - checkout
      - run: npm link
      - run: npm test
      - run: sudo apt-get install -y libsndfile1
      - run: bms-renderer fixtures/cut.bms /tmp/cut.wav
      - run: ./mkdist
      - store_artifacts:
          path: /tmp/circle-artifacts
          destination: artifacts
